spring:
  kafka:
    bootstrap-servers: localhost:9092
    topics:
      - name: new_orders
        num-partitions: 3
        replication-factor: 1
      - name: payed_orders
        num-partitions: 3
        replication-factor: 1
      - name: sent_orders
        num-partitions: 3
        replication-factor: 1
    consumer:
      group-id: logging-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer